In [1]:
!pip install bertopic

Requirement already satisfied: bertopic in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (0.17.3)
Requirement already satisfied: hdbscan>=0.8.29 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from bertopic) (0.8.40)
Requirement already satisfied: umap-learn>=0.5.0 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from bertopic) (0.5.9.post2)
Requirement already satisfied: numpy>=1.20.0 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from bertopic) (2.2.6)
Requirement already satisfied: pandas>=1.1.5 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from bertopic) (2.3.3)
Requirement already satisfied: plotly>=4.7.0 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from bertopic) (6.4.0)
Requirement already satisfied: scikit-learn>=1.0 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from bertopic) (1.7.2)
Requirement already satisfied: sentence-transformers>=0.4.1 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from bertopic) (5.1.2)
Requirement already satisfied: tqdm>=4.41.1 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from bertopic) (4.67.1)
Requirement already satisfied: llvmlite>0.36.0 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from bertopic) (0.45.1)
Requirement already satisfied: scipy>=1.0 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from hdbscan>=0.8.29->bertopic) (1.16.2)
Requirement already satisfied: joblib>=1.0 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from hdbscan>=0.8.29->bertopic) (1.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from pandas>=1.1.5->bertopic) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from pandas>=1.1.5->bertopic) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from pandas>=1.1.5->bertopic) (2025.2)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from plotly>=4.7.0->bertopic) (2.8.0)
Requirement already satisfied: packaging in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from plotly>=4.7.0->bertopic) (25.0)
Requirement already satisfied: six>=1.5 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.1.5->bertopic) (1.17.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn>=1.0->bertopic) (3.6.0)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from sentence-transformers>=0.4.1->bertopic) (4.57.1)
Requirement already satisfied: torch>=1.11.0 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from sentence-transformers>=0.4.1->bertopic) (2.9.0)
Requirement already satisfied: huggingface-hub>=0.20.0 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from sentence-transformers>=0.4.1->bertopic) (0.36.0)
Requirement already satisfied: Pillow in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from sentence-transformers>=0.4.1->bertopic) (11.2.1)
Requirement already satisfied: typing_extensions>=4.5.0 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from sentence-transformers>=0.4.1->bertopic) (4.15.0)
Requirement already satisfied: filelock in c:\users\saikrishna\appdata\roaming\python\python313\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (3.20.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (2025.10.23)
Requirement already satisfied: requests in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (2.32.5)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.6.2)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (2025.9.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.5)
Requirement already satisfied: jinja2 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.1.6)
Requirement already satisfied: setuptools in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (80.9.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.3.0)
Requirement already satisfied: colorama in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from tqdm>=4.41.1->bertopic) (0.4.6)
Requirement already satisfied: numba>=0.51.2 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from umap-learn>=0.5.0->bertopic) (0.62.1)
Requirement already satisfied: pynndescent>=0.5 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from umap-learn>=0.5.0->bertopic) (0.5.13)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from jinja2->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.0.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (2025.10.5)

In [ ]:
from bertopic import BERTopic
import json
import pandas as pd

In [3]:
pip install bertopic scikit-learn sentence-transformers

Requirement already satisfied: bertopic in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (0.17.3)
Requirement already satisfied: scikit-learn in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (1.7.2)
Requirement already satisfied: sentence-transformers in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (5.1.2)
Requirement already satisfied: hdbscan>=0.8.29 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from bertopic) (0.8.40)
Requirement already satisfied: umap-learn>=0.5.0 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from bertopic) (0.5.9.post2)
Requirement already satisfied: numpy>=1.20.0 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from bertopic) (2.2.6)
Requirement already satisfied: pandas>=1.1.5 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from bertopic) (2.3.3)
Requirement already satisfied: plotly>=4.7.0 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from bertopic) (6.4.0)
Requirement already satisfied: tqdm>=4.41.1 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from bertopic) (4.67.1)
Requirement already satisfied: llvmlite>0.36.0 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from bertopic) (0.45.1)
Requirement already satisfied: scipy>=1.8.0 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.16.2)
Requirement already satisfied: joblib>=1.2.0 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from sentence-transformers) (4.57.1)
Requirement already satisfied: torch>=1.11.0 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from sentence-transformers) (2.9.0)
Requirement already satisfied: huggingface-hub>=0.20.0 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from sentence-transformers) (0.36.0)
Requirement already satisfied: Pillow in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from sentence-transformers) (11.2.1)
Requirement already satisfied: typing_extensions>=4.5.0 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: filelock in c:\users\saikrishna\appdata\roaming\python\python313\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (3.20.0)
Requirement already satisfied: packaging>=20.0 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2025.10.23)
Requirement already satisfied: requests in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2.32.5)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.6.2)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2025.9.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from pandas>=1.1.5->bertopic) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from pandas>=1.1.5->bertopic) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from pandas>=1.1.5->bertopic) (2025.2)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from plotly>=4.7.0->bertopic) (2.8.0)
Requirement already satisfied: six>=1.5 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.1.5->bertopic) (1.17.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.5)
Requirement already satisfied: jinja2 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: setuptools in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from torch>=1.11.0->sentence-transformers) (80.9.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: colorama in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from tqdm>=4.41.1->bertopic) (0.4.6)
Requirement already satisfied: numba>=0.51.2 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from umap-learn>=0.5.0->bertopic) (0.62.1)
Requirement already satisfied: pynndescent>=0.5 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from umap-learn>=0.5.0->bertopic) (0.5.13)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\saikrishna\appdata\local\programs\python\python313\lib\site-packages (from requests->transformers<5.0.0,>=4.41.0->sentence-transformers) (2025.10.5)
Note: you may need to restart the kernel to use updated packages.

In [4]:
from sklearn.datasets import fetch_20newsgroups

# Load the full dataset
newsgroups = fetch_20newsgroups(subset='all', remove=('headers', 'footers', 'quotes'))

docs = newsgroups.data

len(docs)

18846

In [7]:
topic_model = BERTopic(embedding_model="all-MiniLM-L6-v2")

In [15]:
docs_small = docs[:2000]   # try 2k docs first
docs_small_clean = [d for d in docs_small if len(d.split()) > 20]
topics, probs = topic_model.fit_transform(docs_small_clean)

In [16]:
topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,0,1601,0_the_to_of_and,"[the, to, of, and, is, in, that, it, for, you]",[In <lsjc8cINNmc1@saltillo.cs.utexas.edu> turp...
1,1,183,1_the_to_and_in,"[the, to, and, in, of, that, he, is, it, on]",[\nNot particularly *in* the World Series. Dur...

In [17]:
topic_model.get_topic(topic=0)

[('the', np.float64(0.12595836209250383)),
 ('to', np.float64(0.07996179373601733)),
 ('of', np.float64(0.07604995574623671)),
 ('and', np.float64(0.0673519339290852)),
 ('is', np.float64(0.054081094647906724)),
 ('in', np.float64(0.0531708708557883)),
 ('that', np.float64(0.05195245734846331)),
 ('it', np.float64(0.04536216236985599)),
 ('for', np.float64(0.03876096458167584)),
 ('you', np.float64(0.03825315098379721))]

In [18]:
topic_model.get_representative_docs(0)

['In <lsjc8cINNmc1@saltillo.cs.utexas.edu> turpin@cs.utexas.edu (Russell Turpin)\n\n\nI regard love as no more or less "benign" than any other Christian does.\nYou are merely expressing "approval" of the consequences I find therein.\nWhich says more about our politics and cultural trappings than about my\n(or any) religion.  "Love" is a highly ambiguous word, of which Christians\ncan write both the "gentle" words Paul uses of it in 1 Corinthians -- in\na passage that even the "conservatives" will quote at you :-) -- and the\nwords of T. S. Eliot in his Pentacost Hymn, "Love is the unfamiliar Name\nthat wove the intolerable shirt of flame ..."\n\nThis is in any case rather to the side of what I was attempting to raise\nin my note, as will become more evident below.\n\n\nblechhh.  I think you are misreading me, rather seriously.  Though,\ngiven my principle that one CANNOT force one\'s own notion of "sin" on\nanother, and my unshakeable "disestablishmentarianism", Russel Turpin\nand others (believers and unbelievers alike) are under no threat of my\nlegislating my own understanding of Christian love.\n\n\nYou misread.  I can do (and have repeatedly done) a complete bill of\naccusation against the Inquisition by exhibiting in as thorough a form\nas anyone might want a demonstration of the harm it has done to human\nbeings (in the first place) and to respect for (let alone love of) "God"\nin near succession.  Please go back to my quoted words above:\n\nThe "possibility that always exists" is that I (or, to revert to proper\ntime sequence, my predecessors over the last several centuries) could\npersuade "Christian B" of my case that the Inquisition *does* indeed\nconstitute an egregious violation of the Law of Love.  I must also note\nthat the majority of Christians HAVE been so persuaded.  By Christian\nargumentation, as well as by secular [both Christian and non-Christian]\nprohibitions.\n\nWhat Mr. Turpin alludes to is a trickier point:\n\n\tA.  I demonstrate the human pain and violation of love involved\n\t    in the Inquisition.\n\n\tB.  The Inquisitor responds that Mother Church must, however\n\t    painful this *seems*, "discipline" her children for their\n\t    own good -- in this case the salvation of their souls (or\n\t    if the tortured heretic will not recant, than by bad example\n\t    "deterring" others from the same loss-of-soul.)\n\n\tA.  I point out that this "justification" of a failure in love\n\t    depends on a highly speculative construal of texts and of\n\t    philosophical assertions that are quite undemonstrable.\n\n\tB.  Burns me at the stake.\n\nMy rhetoric has failed, but the point I am making is sustained.  What is\ngoing on here has a *lot* to do with "cultural baggage."  In this case,\nthe baggage includes a (nearly universal, and absolutely secular) belief\nthat an accused person must prove innocence and that testimony is most\nbelievable if taken under torture.  The elimination of Inqisitorial\npractice (in those places where it *has* been eliminated, or at least\ngreatly reduced) has very little, if anything, to do with the discussion\nof sin in the exchange between A and B.\n\nMr. Turpin is pointing out that, if I am A versus the Grand Inquisitor\'s B,\nthen my persuasion is not very likely to work.  I know this; and in what-\never personal agony, I consign the issue to God and my ghostly defense\nattorney.  So, "one possibility" fails in this case -- as it will fail in\nmay others.  At the other extreme, the "persuasion" will succeed when it\nproperly SHOULD not, if it entails mistaken assumptions I share with the\nInquisitor.  And that is potentially an even more troubling case, in that\nmany of the victims of Inquisition will have "accepted" that they were in\nfact sinful (in such random cases as they may actually have been guilty\nof charges brought against them.)\n\nThe point is that the "persuasion" breaks down when the parties do NOT\nshare enough to agree on all the cultural baggage -- and given the main\nthrust of the Inquisition, against "heresy", it is *bound* to break down\nin precisely the "worst" cases.  The "conservative" (I don\'t think that\nis the right word, BTW) will take refuge in what I attribute to B above,\nthat he is "justified" in causing harm because he *thinks* that works to\na "greater good."  But this is a violent and extravagant REFUSAL to follow\nthe gospel, as if one\'s theories about "sin" entitled one to cast aside\nJesus\' words on dealing with sinners (cf. Matthew 5:39ff).\n\nI am a "radical" Christian *only* in that I take the gospel seriously.\n\n\nWell, the whole *point* of making these the "base" commandments is that\nthey *aren\'t* reducible to rules.  A set of rules is a moral code or a\nlaw code or an algorithm for acting.  Such things can be very helpful\nto individuals or societies -- but not if they are used *instead* of a\npersonal involvement in and responsibility for one\'s actions.  The Great\nCommandment is, more than anything else, a call to act *as if you were\nGod and accepting ultimate responsibility* in your every action.  A\ndemand that I, like most, would rather *not* hear, but it keeps popping\nup nonetheless (along with the reassurance that it is more important\nthat I be open to trying this, than succeeding at it).  "Conservatives"\nmay twist this "act as if you were God" to mean "lay down rules for other\npeople and be as nasty to them as possible if they don\'t keep YOUR rules."\nThey are so insistent (and obvious) about this that they have convinced a\nlot of people (who rightly reject the whole concept!) that such idiocy\nIS how God acts.  That, after all, is the standard accusation "against\nGod" by the atheists here and elsewhere.  That the "conservatives" have\nconfused THEIR manipulative, hoop-jumping notions of coercing other\npeople with the Nature of God is almost the entire content of standard\nAmerican atheism -- and I quite agree with it on this point.\n\n\nAnd different bodies of Christians have, from the beginning, urged\n*different* "ethical systems" (or in some cases, none).  As a result,\nit is bizarre to identify any one of these systems, however popular\n(or infamous) with Christianity.  Christianity DOES NOT HAVE A TORAH.\nIt does not have a QU\'RAN.  Specifically Christian scripture has very\nlittle, if anything, in the way of "commandments" -- so little that\nthe "Christians" who desperately *want* commandments go "mining" for\nthem with almost no support (and thus almost no obvious limitation :-))\nfor their efforts.  The one, single, thing in the gospels which Jesus\nspecifically "gives" as "a commandment" to us is "love one another."\n\n\t[I will be expanding on this point in a reply to Paul Hudson\n\t that I hope to get to in a day or so -- it is quite true that\n\t SOME Christians infer LOTS of commandments from the NT; I\'ll\n\t point out what has to be going on in these inferences, and why\n\t there is a huge amount of "cultural baggage" involved.]\n\nYou are quite right that this is "goo" if one is looking for an ethical\nsystem.\n\nBut why should anyone BE looking for an ethical system, since our\nsociety is eager to hand us one or more no matter what we do?  It\nmay be that we need a principle for the CRITIQUE of ethical systems\n-- in which case I will profer the _agapate allelou_ once again.\n\n\nI think you are begging the question. Why don\'t I and the (myriads\nof) other Christians like me tell you something about Christianity?\n[Nor is this very new in Christianity -- you might want to look up\nthe origins and fundamental doctrines of the Quakers, from the 17th\ncentury onwards, and they are not at all the first to understand the\ngospel in a manner that is congenial to my case.]',

In [20]:
df = pd.DataFrame({'topic': topics, 'document': docs_small_clean})
df.loc[df["topic"] == 0]

      topic                                           document
1         0  My brother is in the market for a high-perform...
2         0  \n\n\n\n\tFinally you said what you dream abou...
3         0  \nThink!\n\nIt's the SCSI card doing the DMA t...
4         0  1)    I have an old Jasmine drive which I cann...
5         0  \n\nBack in high school I worked as a lab assi...
...     ...                                                ...
1779      0  We are making a transition from NextStep to X-...
1780      0  The problems with Catholic liturgy are likely ...
1781      0  \n\nNo matter how "absurd" it is to suggest th...
1782      0  Anyone here know if NCD is doing educational p...
1783      0  I know that the placebo effect is where a pati...

[1601 rows x 2 columns]

In [22]:
#topic_model.visualize_topics()
topic_model.visualize_topics(use_ctfidf=True)

ValueError: zero-size array to reduction operation maximum which has no identity

In [ ]:
topic_model.visualize_barchart()

In [ ]:
topic_model.visualize_hierarchy(hierarchical_topics=hierarchical_topics)